spring.application.name=General-Mechanical-Works
spring.datasource.url=jdbc:mysql://localhost:3306/GeneralMechanicalWorks?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=